<?php require('templates/header.phtml') ?>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <br>
    <table class="table table-hover">
        <thead>
        <tr><th>ID</th><th>Name</th><th>Address</th><th>City</th><th>Postcode</th><th>Lat</th><th>Long</th></tr>



        </thead>
        <tbody>
        <?php foreach ($view->deliveryPointsSet as $deliveryPoint){
            echo '<tr> <td>' . $deliveryPoint->getID() .
            '</td> <td>' .  $deliveryPoint->getName() .
            '</td> <td>' .  $deliveryPoint->getAddress() .
            '</td> <td>' .  $deliveryPoint->getCity() .
            '</td> <td>' .  $deliveryPoint->getPostcode() .
            '</td> <td>' .  $deliveryPoint->getLat() .
            '</td> <td>' .  $deliveryPoint->getLong();
        } ?>
        </tbody>
    </table>
</form>

<?php require('templates/footer.phtml') ?>