<?php require('templates/header.phtml') ?>

<!-- Live Search -->
    <script>
        function showResult(str) {
            if (str.length==0) {
                document.getElementById("livesearch").innerHTML="";
                document.getElementById("livesearch").style.border="0px";
                return;
            }
            var xmlhttp=new XMLHttpRequest();
            xmlhttp.onreadystatechange=function() {
                if (this.readyState==4 && this.status==200) {
                    document.getElementById("livesearch").innerHTML=this.responseText;
                    document.getElementById("livesearch").style.border="1px solid #A5ACB2";
                }
            }
            xmlhttp.open("GET","livesearch.php?q="+str,true);
            xmlhttp.send();
        }
    </script>
    </head>
    <body>

    <form>
        <input type="text" size="30" onkeyup="showResult(this.value)">
        <div id="livesearch"></div>
    </form>

    <!-- Form to display the deliverers deliveries in HTML table -->
    <form action=" <?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <br>
        <table class="table table-hover">
            <thead>
            <tr class="page-break">
                <th>ID</th>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>Postcode</th>
                <th>Lat</th>
                <th>Long</th>
                <th>Status</th>
                <th>Picture</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($view->deliveryPoints as $deliveryPoint) { ?>
                <tr>
                    <td><?php echo $deliveryPoint->getID();  ?></td>
                    <td><?php echo $deliveryPoint->getName(); ?></td>
                    <td><?php echo $deliveryPoint->getAddress(); ?></td>
                    <td><?php echo $deliveryPoint->getCity(); ?></td>
                    <td><?php echo $deliveryPoint->getPostcode(); ?></td>
                    <td><?php echo $deliveryPoint->getLat(); ?></td>
                    <td><?php echo $deliveryPoint->getLong(); ?></td>
                    <td>
                        <!-- Checking if points are delivered already-->
                        <?php if ($deliveryPoint->getStatus() != 5) { ?>
                            <form action="updateStatus.php" method="post">
                                <input type="hidden" name="id" value="<?php echo $deliveryPoint->getID(); ?>">
                                <input type="submit" class="btn btn-info" value="Mark As Delivered">
                            </form>
                        <?php } else { ?>
                            Delivered
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>
            </tbody>

<!--            <tbody>-->
<!--            --><?php //foreach ($view->deliveryPoints as $deliveryPoint) {
//                echo '<tr> <td>' . $deliveryPoint->getID() .
//                    '</td> <td>' . $deliveryPoint->getName() .
//                    '</td> <td>' . $deliveryPoint->getAddress() .
//                    '</td> <td>' . $deliveryPoint->getCity() .
//                    '</td> <td>' . $deliveryPoint->getPostcode() .
//                    '</td> <td>' . $deliveryPoint->getLat() .
//                    '</td> <td>' . $deliveryPoint->getLong() .
//                    '</td> <td>' . $deliveryPoint->getStatus() . " " .
//                    '<div class="btn-group" role="group" aria-label="Record Actions"><a class="btn btn-info" href="updateStatus.php' . $deliveryPoint->getID() . '">Delivered</a>&nbsp; </div></td>';
////                    '</td><td>' . '<img src="images/' . $deliveryPoint->getPhotoName() . '" alt="no picture" />' . '</td>';
//            } ?>
<!--            </tbody>-->
        </table>

        <nav aria-label="Page navigation">
            <ul class="pagination">
                <?php
                $startPage = max(1, $view->currentPage - 4);
                $endPage = min($startPage + 9, $view->totalPages);

                //Previous Page buttons
                if ($view->currentPage > 1) {
                    echo '<li class="page-item disabled"><span class="page-link">Previous</span>';
                }

                //Limiting page numbers to 10
                for ($i = $startPage; $i <= $endPage; $i++) {
                    echo '<li class="page-item ' . ($i == $view->currentPage ? 'active' : '') . '">
                            <a class="page-link" href="?page=' . $i . '">' . $i . '</a>
                            </li>';
                }

                //Next Page Link
                if ($view->currentPage < $view->totalPages) {
                    echo '<li class="page-item"><a class="page-link" href="?page=' .($view->currentPage + 1) . '">Next</a></li>';
                } else {
                    echo '<li class="page-item disabled"><span class="page-link">Next</span></li>';
                }

                ?>
            </ul>
        </nav>
    </form>
<?php require('templates/footer.phtml') ?>