<?php require('templates/header.phtml') ?>

    <h3>Welcome to my Parcel Buddy Website</h3>

    <h3>This website is a data driven online client server system called ParcelBuddy aimed at logging and tracking
        parcel deliveries for a small
        delivery company and their drivers.</h3>
    <br>
    <p>This system was built using PHP, MySQL and HTML/CSS using an OOP approach to the code and a Model-View-Controller design pattern.</p>

<?php require('templates/footer.phtml') ?>