<?php require ('templates/header.phtml');

foreach ($view->deliveryUserSet as $deliveryUser){
    $id = $deliveryUser->getUserID();
    $name = $deliveryUser->getUsername();
    $password = $deliveryUser->getPassword();
    $usertype = $deliveryUser->getUsertype();
} ?>

<form action=" <?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-control">
    <label for="id">ID:</label>
    <input type="text" id="id" name="id" value="<?php echo $id ?>" class="form-control" readonly>
    <label for="name">Username:</label>
    <input type="text" id="name" name="name" value="<?php echo $name ?>" class="form-control" required>
    <label for="password">Password:</label>
    <input type="text" id="password" name="password" value="<?php echo $password?>" class="form-control" required>
    <label for="usertype">Usertype:</label>
    <input type="text" id="usertype" name="usertype" value="<?php echo $usertype ?>" class="form-control" required>
    <input type="submit" name="updateUser" class="form-control" required>
</form>